### ISSUE TITLE
간헐적으로 postlist 불러오기 오류

### ISSUE THREAD

**Issue by GitPJS** [8Team-Final-Project/honey-combination-Frontend#8]
![image](https://user-images.githubusercontent.com/90602950/141776612-3a11021e-c1a8-488e-958e-a7da687af0f5.png)

어떤 조건에서 뜨는지 모르겠는데 가끔씩 에러 발생 
꿀조합이나 이벤트페이지에서 postlist를 불러올때 뜸

**Comment by waterhumanB** [comment]
게시물 추가할 때 배열 형태로 받지 못한 오류
그래서 배열 형태로 받아 오게 바꿔서 해결
